/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as FixturesRouteImport } from './routes/fixtures'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as ScorersRouteImport } from './routes/scorers'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as TableRouteImport } from './routes/table'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as MatchesIdRouteImport } from './routes/matches.$id'
import { Route as TeamsSlugRouteImport } from './routes/teams.$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const FixturesRoute = FixturesRouteImport.update({
  id: '/fixtures',
  path: '/fixtures',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const ScorersRoute = ScorersRouteImport.update({
  id: '/scorers',
  path: '/scorers',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const TableRoute = TableRouteImport.update({
  id: '/table',
  path: '/table',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesIdRoute = MatchesIdRouteImport.update({
  id: '/matches/$id',
  path: '/matches/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsSlugRoute = TeamsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TeamsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/announcements': typeof AnnouncementsRoute
  '/fixtures': typeof FixturesRoute
  '/login': typeof LoginRoute
  '/results': typeof ResultsRoute
  '/scorers': typeof ScorersRoute
  '/stats': typeof StatsRoute
  '/table': typeof TableRoute
  '/teams': typeof TeamsRouteWithChildren
  '/matches/$id': typeof MatchesIdRoute
  '/teams/$slug': typeof TeamsSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/announcements': typeof AnnouncementsRoute
  '/fixtures': typeof FixturesRoute
  '/login': typeof LoginRoute
  '/results': typeof ResultsRoute
  '/scorers': typeof ScorersRoute
  '/stats': typeof StatsRoute
  '/table': typeof TableRoute
  '/teams': typeof TeamsRouteWithChildren
  '/matches/$id': typeof MatchesIdRoute
  '/teams/$slug': typeof TeamsSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/announcements': typeof AnnouncementsRoute
  '/fixtures': typeof FixturesRoute
  '/login': typeof LoginRoute
  '/results': typeof ResultsRoute
  '/scorers': typeof ScorersRoute
  '/stats': typeof StatsRoute
  '/table': typeof TableRoute
  '/teams': typeof TeamsRouteWithChildren
  '/matches/$id': typeof MatchesIdRoute
  '/teams/$slug': typeof TeamsSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/announcements'
    | '/fixtures'
    | '/login'
    | '/results'
    | '/scorers'
    | '/stats'
    | '/table'
    | '/teams'
    | '/matches/$id'
    | '/teams/$slug'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/announcements'
    | '/fixtures'
    | '/login'
    | '/results'
    | '/scorers'
    | '/stats'
    | '/table'
    | '/teams'
    | '/matches/$id'
    | '/teams/$slug'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/announcements'
    | '/fixtures'
    | '/login'
    | '/results'
    | '/scorers'
    | '/stats'
    | '/table'
    | '/teams'
    | '/matches/$id'
    | '/teams/$slug'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AnnouncementsRoute: typeof AnnouncementsRoute
  FixturesRoute: typeof FixturesRoute
  LoginRoute: typeof LoginRoute
  ResultsRoute: typeof ResultsRoute
  ScorersRoute: typeof ScorersRoute
  StatsRoute: typeof StatsRoute
  TableRoute: typeof TableRoute
  TeamsRoute: typeof TeamsRouteWithChildren
  MatchesIdRoute: typeof MatchesIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fixtures': {
      id: '/fixtures'
      path: '/fixtures'
      fullPath: '/fixtures'
      preLoaderRoute: typeof FixturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scorers': {
      id: '/scorers'
      path: '/scorers'
      fullPath: '/scorers'
      preLoaderRoute: typeof ScorersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/table': {
      id: '/table'
      path: '/table'
      fullPath: '/table'
      preLoaderRoute: typeof TableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/$id': {
      id: '/matches/$id'
      path: '/matches/$id'
      fullPath: '/matches/$id'
      preLoaderRoute: typeof MatchesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$slug': {
      id: '/teams/$slug'
      path: '/$slug'
      fullPath: '/teams/$slug'
      preLoaderRoute: typeof TeamsSlugRouteImport
      parentRoute: typeof TeamsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TeamsRouteChildren {
  TeamsSlugRoute: typeof TeamsSlugRoute
}

const TeamsRouteChildren: TeamsRouteChildren = {
  TeamsSlugRoute: TeamsSlugRoute,
}

const TeamsRouteWithChildren = TeamsRoute._addFileChildren(TeamsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AnnouncementsRoute: AnnouncementsRoute,
  FixturesRoute: FixturesRoute,
  LoginRoute: LoginRoute,
  ResultsRoute: ResultsRoute,
  ScorersRoute: ScorersRoute,
  StatsRoute: StatsRoute,
  TableRoute: TableRoute,
  TeamsRoute: TeamsRouteWithChildren,
  MatchesIdRoute: MatchesIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
